services:
  # MCP Proxy service - configurable transport via .env
  mcp-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./servers.json:/app/servers.json:ro
      - ./creds:/creds
    env_file:
      - .env
    #tty: true
    restart: unless-stopped

  zrok:
    # currently requires the old version as the server hasn't been updated yet
    image: openziti/zrok:1.0.8
    volumes:
      - zrok-data:/zrok/.zrok
    restart: unless-stopped
    environment:
      HOME: /zrok
      PFXLOG_NO_JSON: "true"
    entrypoint: []
    tty: true
    secrets:
      - zrok_token
    user: root
    links:
      - mcp-proxy

    command: >
      bash -c "

      trap 'echo Stopping zrok service...; zrok release ${ZROK_NAME} || true;  zrok disable || true; echo Zrok service stopped.' EXIT;

      (zrok -p disable || true);
      zrok config set apiEndpoint ${ZROK_API_ENDPOINT} &&
      zrok enable -d '${ZROK_ENV_NAME}' $(cat /run/secrets/zrok_token) &&
      (zrok release ${ZROK_NAME} || true) &&
      zrok reserve public -n ${ZROK_NAME} http://mcp-proxy:8001 &&
      zrok share reserved ${ZROK_NAME} --headless
      "

secrets:
  zrok_token:
    environment: ZROK_TOKEN

volumes:
  zrok-data: