name: Docker Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        load: true
        tags: fastmcp-proxy:test-proxy
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test Docker image startup (proxy)
      run: |
        # Test that the proxy image can start without errors
        docker run --rm -d --name test-proxy fastmcp-proxy:test-proxy http --port 8001 --host 0.0.0.0 &
        CONTAINER_ID=$!
        
        # Wait a moment for startup
        sleep 3
        
        # Check if container is still running
        if docker ps | grep -q test-proxy; then
          echo "✓ Proxy container started successfully"
          docker stop test-proxy
        else
          echo "✗ Proxy container failed to start"
          docker logs test-proxy || true
          exit 1
        fi

